### PR TITLE
 [Chore] estatico-boilerplate: Optimized global client-side namespace

### PR DESCRIPTION
**Pull request by backflip**
- Extracted `window.estatico` definition into separate `helpers/namespace.js` file. This allows to change a single file when changing the namespace (we often want to use the project name instead of `estatico`).
- Renamed `EstaticoApp` into `App` since we should decouple the build system from the frontend code. Otherwise people might get confused that they *have* to use the JS setup in the boilerplate when using the build system.

### CODE REVIEW

**Comment by orioltf** [comment]
Does it still make sense we to keep referencing to `window`?

**Comment by backflip** [comment]
@orioltf, not necessarily, but I would prefer to discuss the general architecture separately, if that's fine with you. This PR is only about improving the current state in a backwards-compatible way.

BTW: For future reference: Exposing things in the global namespace turned out to be pretty useful in some of my ongoing project, i.e. allowing engineers from the client to programmatically initialize or destroy modules. But there might be another way of allowing this.

**Comment by orioltf** [comment]
I fully agree.

**Review by orioltf — COMMENTED** [review]
Well done! 👌 😃

**Review by orioltf — APPROVED** [review]

**Pull request merged**
